---
locations:
  - name: Calgary
    climate: Moderate
    distance: 500
    visited: Yes
  - name: Flaming Spokane
    climate: Hot
    distance: 250
    visited: No
  - name: Salt Lake City
    climate: Warm
    distance: 350
    visited: No
  - name: Skagway
    climate: Cold
    distance: 800
    visited: Yes