---
locations:
  - climate: Moderate
    distance: 500
    visited: Yes
  - climate: Hot
    distance: 250
    visited: No
  - climate: Warm
    distance: 350
    visited: No
  - climate: Cold
    distance: 800
    visited: Yes